name: Build and deploy Zola site

on:
push:
branches: ["master"]

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4
    with:
      submodules: true

  - name: Install Zola
    uses: taiki-e/install-action@zola

  - name: Build site
    run: zola build --base-url "https://roderic.me"

  - name: Deploy to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./public
      publish_branch: gh-pages

